language: python
os: linux
dist: xenial

before_install:
  - env
  - openssl version
  - python -c "import ssl; print(ssl.OPENSSL_VERSION)"

install:
  - ./ci/install.sh

script:
  - ./ci/run.sh
  - ./ci/upload_coverage.sh

cache:
  directories:
  - ${HOME}/.cache

notifications:
  email: false

env:
  global:
    - PYTHONWARNINGS=always::DeprecationWarning

    - PYPI_USERNAME=hip
    # PYPI_PASSWORD is set in Travis control panel.

jobs:
  include:
    # Unit tests
    - python: 3.5
      env: NOX_SESSION=test-3.5
    - python: 3.6
      env: NOX_SESSION=test-3.6
    - python: 3.7
      env: NOX_SESSION=test-3.7
    - python: 3.8-dev
      env: NOX_SESSION=test-3.8
    - python: pypy
      env: NOX_SESSION=test-pypy
    - python: pypy3
      env: NOX_SESSION=test-pypy3

    - python: 2.7
      env: NOX_SESSION=google_brotli-2.7
    - python: 3.7
      env: NOX_SESSION=google_brotli-3.7

stages:
  - name: test
    if: tag IS blank

  # Run integration tests for release candidates
  - name: integration
    if: type = pull_request AND head_branch =~ ^release-[\d.]+$ AND tag IS blank

  # Deploy on any tags
  - name: deploy
    if: tag IS present AND tag =~ /^(\d+\.\d+(?:.\d+)?)$/ AND repo = python-trio/hip
